#!/bin/bash
set -e

# Generate host keys if not present
ssh-keygen -A

# Setup authorized_keys from bind-mounted keys (.keys/ generated by setup-keys.sh)
if [ -d /ssh-keys ] && [ -f /ssh-keys/id_read.pub ]; then
    # Build authorized_keys with 4 entries
    mkdir -p /home/e2e-user/.ssh

    # Entry 1: id_read → level=read, config with auth
    echo "command=\"/usr/local/bin/ssh-frontiere --level=read --config=/etc/ssh-frontiere/config.toml\",restrict $(cat /ssh-keys/id_read.pub)" > /home/e2e-user/.ssh/authorized_keys

    # Entry 2: id_ops → level=ops, config with auth
    echo "command=\"/usr/local/bin/ssh-frontiere --level=ops --config=/etc/ssh-frontiere/config.toml\",restrict $(cat /ssh-keys/id_ops.pub)" >> /home/e2e-user/.ssh/authorized_keys

    # Entry 3: id_noauth → level=read, config without auth
    echo "command=\"/usr/local/bin/ssh-frontiere --level=read --config=/etc/ssh-frontiere/config-noauth.toml\",restrict $(cat /ssh-keys/id_noauth.pub)" >> /home/e2e-user/.ssh/authorized_keys

    # Entry 4: id_simpleauth → level=read, config with auth but no challenge_nonce (simple mode)
    echo "command=\"/usr/local/bin/ssh-frontiere --level=read --config=/etc/ssh-frontiere/config-simple-auth.toml\",restrict $(cat /ssh-keys/id_simpleauth.pub)" >> /home/e2e-user/.ssh/authorized_keys

    chmod 600 /home/e2e-user/.ssh/authorized_keys
    chown e2e-user:e2e-user /home/e2e-user/.ssh/authorized_keys
fi

# Start sshd in foreground
exec /usr/sbin/sshd -D -e
