#!/bin/bash
set -e

# Keys are generated by init-keys container in the shared volume
mkdir -p ~/.ssh

# Copy private keys locally
cp /ssh-keys/id_read ~/.ssh/id_read
cp /ssh-keys/id_ops ~/.ssh/id_ops
cp /ssh-keys/id_noauth ~/.ssh/id_noauth
cp /ssh-keys/id_simpleauth ~/.ssh/id_simpleauth
chmod 600 ~/.ssh/id_read ~/.ssh/id_ops ~/.ssh/id_noauth ~/.ssh/id_simpleauth

# SSH config: disable strict host key checking for test network
cat > ~/.ssh/config << 'SSHCONFIG'
Host server
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR

Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR
SSHCONFIG
chmod 600 ~/.ssh/config

exec "$@"
